import React, { useState } from 'react';
import { Course, Category } from '../../core/entities';
import { Search, Plus, ChevronDown } from 'lucide-react';
import { CourseCard } from '../components/course';
import { PageLoadingSpinner } from '../components/common/LoadingSpinner';

interface CoursesPageProps {
  courses: Course[];
  categories: Category[];
  selectedCategory: string;
  onSelectCategory: (catId: string) => void;
  searchQuery: string;
  onSearchChange: (query: string) => void;
  onSelectCourse: (course: Course) => void;
  onCreateCourseClick: () => void;
  onDeleteCourse?: (course: Course) => void;
  isLoading?: boolean;
}

export const CoursesPage: React.FC<CoursesPageProps> = ({
  courses,
  categories,
  selectedCategory,
  onSelectCategory,
  searchQuery,
  onSearchChange,
  onSelectCourse,
  onCreateCourseClick,
  onDeleteCourse,
  isLoading = false,
}) => {
  const [visibleLimit, setVisibleLimit] = useState(6);

  if (isLoading) {
    return <PageLoadingSpinner message="Đang tải danh sách khóa học..." />;
  }

  // Filter courses by category & search term
  const filteredCourses = courses.filter((c) => {
    const matchesCategory =
      selectedCategory === 'all' ||
      c.categoryId === selectedCategory ||
      c.category.toLowerCase() === selectedCategory.toLowerCase();
    const query = searchQuery.toLowerCase().trim();
    const matchesSearch =
      !query ||
      c.title.toLowerCase().includes(query) ||
      c.description.toLowerCase().includes(query) ||
      c.category.toLowerCase().includes(query);
    return matchesCategory && matchesSearch;
  });

  const displayedCourses = filteredCourses.slice(0, visibleLimit);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 animate-in fade-in duration-200">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold text-[#1B1F2E] dark:text-white font-display">
            My Courses
          </h1>
          <p className="text-xs sm:text-sm text-[#5A6478] dark:text-[#CBD5E1] mt-1">
            Manage and study courses generated by AI from YouTube or saved in your library
          </p>
        </div>

        {/* Search & Create Bar */}
        <div className="flex items-center gap-3">
          <div className="relative flex-1 sm:w-64">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-[#95A0B4]" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => {
                onSearchChange(e.target.value);
                setVisibleLimit(6);
              }}
              placeholder="Search courses..."
              className="w-full pl-10 pr-4 py-2.5 text-xs rounded-full bg-white dark:bg-[#1E293B] border border-[#E4E8F0] dark:border-[#334155] text-slate-900 dark:text-white placeholder-slate-400 focus:ring-2 focus:ring-[#2E68FF] focus:outline-none transition-all shadow-xs"
            />
          </div>

          <button
            onClick={onCreateCourseClick}
            className="px-5 py-2.5 rounded-full bg-[#2E68FF] hover:bg-blue-600 text-white text-xs font-bold flex items-center gap-2 shadow-sm shrink-0 transition-colors cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>Create Course</span>
          </button>
        </div>
      </div>

      {/* Category Filter Pills (Scrollable Bar) */}
      <div className="flex items-center gap-2 overflow-x-auto py-2 no-scrollbar">
        {categories.map((cat) => (
          <button
            key={cat.id}
            onClick={() => {
              onSelectCategory(cat.id);
              setVisibleLimit(6);
            }}
            className={`px-4 py-2 rounded-full text-xs font-semibold whitespace-nowrap transition-colors cursor-pointer ${
              selectedCategory === cat.id
                ? 'bg-[#2E68FF] text-white shadow-xs'
                : 'bg-white dark:bg-[#1E293B] text-[#5A6478] dark:text-[#CBD5E1] border border-[#E4E8F0] dark:border-[#334155] hover:border-slate-300'
            }`}
          >
            {cat.name}
          </button>
        ))}
      </div>

      {/* Courses Grid */}
      {displayedCourses.length === 0 ? (
        <div className="text-center py-16 bg-white dark:bg-[#1E293B] rounded-3xl border border-[#E4E8F0] dark:border-[#334155] p-8 space-y-4 shadow-sm">
          <p className="text-lg font-extrabold text-[#1B1F2E] dark:text-white font-display">No courses found</p>
          <p className="text-xs text-slate-500 max-w-sm mx-auto">
            Try adjusting your search query or filter to find what you're looking for.
          </p>
          <button
            onClick={() => {
              onSelectCategory('all');
              onSearchChange('');
              setVisibleLimit(6);
            }}
            className="px-6 py-2.5 rounded-full bg-[#2E68FF] hover:bg-blue-600 text-white text-xs font-bold transition-all shadow-md"
          >
            View All
          </button>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-5">
            {displayedCourses.map((course) => (
              <CourseCard
                key={course.id}
                course={course}
                onSelectCourse={() => onSelectCourse(course)}
                onDeleteCourse={onDeleteCourse}
              />
            ))}
          </div>

          {/* Load More Button */}
          {filteredCourses.length > visibleLimit && (
            <div className="text-center pt-6">
              <button
                onClick={() => setVisibleLimit((prev) => prev + 6)}
                className="px-8 py-3.5 rounded-full bg-white dark:bg-[#1E293B] text-[#2E68FF] dark:text-[#5B8CFF] border border-[#2E68FF]/30 dark:border-[#5B8CFF]/30 font-extrabold text-xs uppercase tracking-wider shadow-md hover:bg-blue-50 dark:hover:bg-blue-950/50 hover:scale-105 transition-all inline-flex items-center gap-2 cursor-pointer"
              >
                <span>Load More Courses ({filteredCourses.length - visibleLimit} more)</span>
                <ChevronDown className="w-4 h-4" />
              </button>
            </div>
          )}
        </>
      )}
    </div>
  );
};
